spring.application.name=homeplusbackend

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/homeplus
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# JWT Configuration
jwt.secret=your_secret_key_change_this_in_production_at_least_32_chars
jwt.expiration=86400000